# Generated by Django 4.0.7 on 2023-03-14 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Realizado', 'Default'), ('Em andamento', 'In Progress'), ('Entregue', 'Delivered')], default='Realizado', max_length=20)),
                ('price', models.IntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='address.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_orders', to='cart.cart')),
            ],
        ),
    ]
